title: alt-bespoke-docs
description: alternative <a href="https://severak.github.io/alt-bespoke-docs/">documentation</a> for <a href="https://www.bespokesynth.com/">Bespoke synth</a>
show_downloads: false
theme: jekyll-theme-midnight
