title: alt-bespoke-docs
description: archived - refer to <a href="https://bespokesynth.github.io/BespokeSynthDocs/">Bespoke synth community documentation</a>
show_downloads: false
theme: jekyll-theme-midnight
